### ISSUE TITLE
Feature: Markdown

### ISSUE THREAD

**Issue by bun-dev** [MexHigh/Gotify-Webhooks-Plugin#1]
Is there any chance of this supporting markdown instead of raw json strings to gotify? thanks
![Screenshot_20240625-072312_Gotify](https://github.com/MexHigh/Gotify-Webhooks-Plugin/assets/34141271/d741c0ce-b7bf-4174-a1a6-cd7cea1b260b)

**Comment by MexHigh** [comment]
Could you elaborate how you like the payload to be displayed and can you give examples? Your service (Grafana?) seems to posts JSON to the webhook.

**Comment by s1oz** [comment]
> 您能否详细说明您希望如何显示有效负载并举例说明？您的服务（Grafana？）似乎将 JSON 发布到 webhook。



> Could you elaborate how you like the payload to be displayed and can you give examples? Your service (Grafana?) seems to posts JSON to the webhook.

![QQ截图20240806155552](https://github.com/user-attachments/assets/ff610f7e-80c2-4b5f-953e-6be504df42f0)
Do you support Markdown syntax?
The following command doesn't display correctly after I use it:
```
"Hello: ![](https://gotify.net/img/logo.png)"
```

**Comment by MexHigh** [comment]
No there is currently no support for it, since I don't know which service uses markdown as webhook payload. Is there any particular reason why you try to POST markdown to Gotify via webhooks instead of just using the API? 

The following call should work for displaying Markdown:

```bash
curl -X POST "https://<host>/message?token=<token>" -H "Content-Type: application/json" \
  -d "{ \"title\": \"Hello World\", \"message\": \"# Markdown\n\n- list\n\n- list2\", \"extras\": { \"client::display\": { \"contentType\": \"text/markdown\" } } }"
```

![image](https://github.com/user-attachments/assets/030599c9-8f2f-4a59-81b6-d52dd75604db)

**Comment by s1oz** [comment]
> No there is currently no support for it, since I don't know which service uses markdown as webhook payload. Is there any particular reason why you try to POST markdown to Gotify via webhooks instead of just using the API?
> 
> The following call should work for displaying Markdown:
> 
> ```shell
> curl -X POST "https://<host>/message?token=<token>" -H "Content-Type: application/json" \
>   -d "{ \"title\": \"Hello World\", \"message\": \"# Markdown\n\n- list\n\n- list2\", \"extras\": { \"client::display\": { \"contentType\": \"text/markdown\" } } }"
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/50419884/355567458-030599c9-8f2f-4a59-81b6-d52dd75604db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5ODk3MTQsIm5iZiI6MTcyMjk4OTQxNCwicGF0aCI6Ii81MDQxOTg4NC8zNTU1Njc0NTgtMDMwNTk5YzktOGYyZi00YTU5LTgxYjYtZDUyZGQ3NTYwNGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAwMTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZjRhYzQ2OGM1MjEzZjRkMmJjODU1Mjg5ZjBkMGI0NGE1ODgyNTJhMzlkY2E1MjBkODZjYzI4ZjcwZDA3NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U5oT6H28-rLBEqwprLM-Q-_0wDVVKaNR4LQgZFz02L0)

Due to the delayed notifications from Synology's official `Ds cam` app, I found in the [official documentation](https://kb.synology.com/en-my/SurveillanceStation/help/SurveillanceStation/notification_webhook?version=9) that webhook support is available. I would like to use Gotify to push notifications and images. Could you please consider adding support for this feature?

Thank you!

**Comment by MexHigh** [comment]
Can you set the content type in the Surveillance Station? I could add a condition for `text/markdown` and try to use Gotifys Markdown display option for the payload.

Will try that out next week.

**Comment by s1oz** [comment]
> Can you set the content type in the Surveillance Station? I could add a condition for `text/markdown` and try to use Gotifys Markdown display option for the payload.
> 
> Will try that out next week.

It cannot be set directly to `text/markdown`; only the following options are available:
```
POST
PUT
```
```
application/x-www-form-urlencoded
application/json
text/plain
```

**Comment by MexHigh** [comment]
Can you set additional request headers? Otherwise, this will be ugly to implement I think.

**Comment by MexHigh** [comment]
Done! Markdown is now supported. You can set the content type via a query parameter (e.g. `https://.../webhook?content-type=text/markdown`). You can also take a look at the README for other options.

You can grab the plugin here: https://git.leon.wtf/leon/gotify-webhooks-plugin/-/packages/15

Please let me know if this works for you!
